version: '3.7'

services:
  tgbot:
    build: ./
    restart: always
    command: bash entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13.1
    restart: always
    volumes:
      - faceit_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
    # [порт компьютера]:[порт контейнера]
      - 5435:5432

volumes:
  faceit_postgres_data: